---
title: "Run analysis"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source("R/function_library.R")

conf = list(
  # Maximum amount of memory to allow rJava heap to use for bartMachine.
  # Defaults to 16g but use options(java.mem = "20g") to change.
  java_mem = getOption("java.mem", "16g")
)

# Load/install necessary packages.
startup(auto_install = FALSE, verbose = TRUE, java_mem = conf$java_mem)
# Load all .R files in R/
ck37r::load_all_code("R")
```

## Configure analysis

```{r config}
(conf = c(conf, list(
  input_dir_counterfactuals = "data-raw/practice-censoring",
  input_file_covariates = "data-raw/x.csv",
  output_file_ate = "exports/ate-test.csv",
  # IPO = Individual potential outcomes
  output_dir_ipo = "exports/ipo-test",
)))

results = list()
```

## Analysis: revere

```{r analysis_revere}
results$revere =
  run_analysis(
    input_dir_counterfactuals = conf$input_dir_counterfactuals,
    input_file_covariates = conf$input_file_covariates,
    tmle_wrapper = wrapper_revere_basic,
    # specific_files = c("d1546da12d8e4daf8fe6771e2187954d"),
    verbose = TRUE)
```

## Evaluate: revere

Evaluate our estimates if we have counterfactual files.

```{r eval_estimates}
if (exists("results") && "revere" %in% names(results) &&
    "cf_files" %in% names(results$revere) && length(results$revere$cf_files) > 0L) {
  stats = evaluate_estimates(results$revere, verbose = TRUE)
  print(stats)
  save(results, stats,
       file = "data/results-stats-revere.RData")
}
```

25% coverage :(

## Analysis: revere glm

Revere with only GLM + mean as learners.

```{r analysis_revere_glm}

# Generate analyses
results$revere_glm =
  run_analysis(
    input_dir_counterfactuals = conf$input_dir_counterfactuals,
    input_file_covariates = conf$input_file_covariates,
    tmle_wrapper = wrapper_revere_glm,
    verbose = TRUE)
```

## Evaluate: revere

Evaluate our estimates if we have counterfactual files.

```{r eval_revere_glm}
if (exists("results") && "revere_glm" %in% names(results) &&
    "cf_files" %in% names(results$revere_glm) && length(results$revere_glm$cf_files) > 0L) {
  stats = evaluate_estimates(results$revere_glm, verbose = TRUE)
  print(stats)
  save(results, stats,
       file = "data/results-stats-revere-glm.RData")
}
```

50% coverage!

## Analysis: tmle-glm

```{r analysis_tmle_glm}
results$tmle_glm =
  run_analysis(
    input_dir_counterfactuals = conf$input_dir_counterfactuals,
    input_file_covariates = conf$input_file_covariates,
    tmle_wrapper = wrapper_tmle_glm,
    # Need to do stratified cross-validation. Should fit SL outside of tmle.
    #specific_files = c("9333a461d3944d089ef60cdf3b88fd40"),
    verbose = TRUE)
```

## Evaluate: tmle-glm

```{r eval_tmle_glm}
if (exists("results") && "tmle_glm" %in% names(results) &&
    "cf_files" %in% names(results$tmle_glm) && length(results$tmle_glm$cf_files) > 0L) {
  stats = evaluate_estimates(results$tmle_glm, verbose = TRUE)
  print(stats)
  save(results, stats,
       file = "data/results-stats-tmle-glm.RData")
}
```

## Analysis: tmle

```{r analysis_tmle}
results$tmle =
  run_analysis(
    input_dir_counterfactuals = conf$input_dir_counterfactuals,
    input_file_covariates = conf$input_file_covariates,
    tmle_wrapper = wrapper_tmle_better,
    # Need to do stratified cross-validation. Should fit SL outside of tmle.
    specific_files = c("9333a461d3944d089ef60cdf3b88fd40"),
    verbose = TRUE)
```

## Evaluate: tmle

```{r eval_tmle}
if (exists("results") && "tmle" %in% names(results) &&
    "cf_files" %in% names(results$tmle) && length(results$tmle$cf_files) > 0L) {
  stats = evaluate_estimates(results$tmle, verbose = TRUE)
  print(stats)
  save(results, stats,
       file = "data/results-stats-tmle.RData")
}
```

## Create output files

```{r create_output}
output_files =
  create_output_files(
    results,
    output_file_ate = conf$output_file_ate,
    output_dir_ipo = conf$output_dir_ipo,
    verbose = TRUE)
```

## Submit entry

```{r submit_entry}
# Submit entry programmatically using R.
```